[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "두송이꽃"
authors = [{name = "두송이꽃", email = "bjh13579@gmail.com"}]
dynamic = ["version", "description"]
